name: Update GitHub Org Configuration
on:
  schedule:
    - cron: "0 3 * * *"
  push:
    paths:
      - "peribolos.yaml"
    branches:
      - main

# Declare default permissions as read only.
permissions: read-all

jobs:
  manage-github-org-config-workflow:
    name: manage-github-org-config-workflow
    uses: crowsnest-security/.github/.github/workflows/manage-github-org.yml@main
    secrets:
      PERIBOLOS_TOKEN: ${{ secrets.PERIBOLOS_TOKEN }}
    with:
      APPLY_CHANGES: true
